name: audio_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_svg: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: DM Sans
      fonts:
        - asset: /Users/pedro/programacao/flutter/audio_app/Assets/Fonts/DMSans-Regular.ttf
        - asset: /Users/pedro/programacao/flutter/audio_app/Assets/Fonts/DMSans-Bold.ttf
          weight: 700
        - asset: /Users/pedro/programacao/flutter/audio_app/Assets/Fonts/DMSans-Italic.ttf
          style: italic  
  assets:
    - assets/icons/
    - assets/images/background.jpg
